/* eslint-disable react/no-unescaped-entities */

export default function Terms() {
  return (
    <div className='d-flex flex-column align-items-center px-4'>
        <h1 className="flex-center">Roomster Corp. Terms of Use</h1>
        <h5>These Roomster Terms of Use apply when you access, use or visit the Roomster website
            located at www.roomster.com (the “Site”), the associated mobile application, and the services 
            provided through the Site and mobile application that provide apartment renters,
            seekers, roommates, and room renters an opportunity to connect with each other
            (the Site, the mobile application and these services constituting the "Service"). 
            The Service is provided to you by Roomster Corp. (referred to in these Terms of Use as “Roomster” “we,” “us” and “our”).
            You must agree to these Terms of Use in order to use the Service. If you do not agree with these Terms of Use at any 
            time, please cease use of the Service.</h5>
            <i><p> <u className="text-primary">Notice Regarding Dispute Resolution:</u> These Terms of Use contain provisions that govern how claims you and we may have against each other are resolved (see Section 14 below), including an agreement and obligation to arbitrate disputes, which will, subject to limited exceptions, require you to submit claims you have against us to binding arbitration, unless you opt-out in accordance with Section 14(E). Unless you opt-out of arbitration: (a) you will only be permitted to pursue claims against us on an individual basis, not as part of any class or representative action or proceeding and (b) you will only be permitted to seek relief (including monetary, injunctive, and declaratory relief) on an individual basis.</p></i>
            <p>Updates to these Terms of Use. We may modify these Terms of Use from time to time. We will notify you of material changes to these Terms of Use by posting the amended terms on the Service at least thirty (30) days before the effective date of the changes. If you do not agree with the proposed changes, you should discontinue your use of the Service prior to the time the new Terms of Use take effect. If you continue using the Service after the new terms take effect, you will be bound by the modified Terms of Use.
Privacy Policy. In connection with your use of the Service, please review our Privacy Policy, located at https://www.roomster.com/privacy, to understand how we use information we collect from you when you access, visit or use the Service. The Privacy Policy is part of and is governed by these Terms of Use and by agreeing to these Terms of Use, you agree to be bound by the terms of the Privacy Policy and agree that we may use information collected from you in accordance with its terms.
Member Accounts and Registration.
Member Registration. You can visit and browse the Service without becoming a registered member of the Service, but you will not be able to post listings on the Service, respond to listings on the Service, access interactive portions of the Service or otherwise post Contributions (as defined in Section 6(A) below) unless you are a registered member of the Service. You can become a registered member of the Service by logging in to the Service through Facebook Connect. You therefore must have a valid and active account with Facebook in order to become a registered member of the Service. By logging in to the Service through Facebook Connect, you grant us permission to access and use the information that Facebook shares with us when you register to use the Service through Facebook Connect, in accordance with the privacy policy of Facebook and the privacy settings that are applicable to your Facebook account. For more details on how you can manage the information provided to us by Facebook, please review the privacy settings applicable to your Facebook account. We reserve the right to reject your member registration if, based on information provided to us through Facebook, we determine that your Facebook account is invalid, inactive, or is not associated with an individual person. If we reject your member registration, and you believe we have rejected your member registration in error, you may contact us at help@roomster.com.
Member Accounts. If you sign up to become a registered member of the Service, you agree: (a) to provide true, accurate, current and complete information about yourself as prompted by the Service’s registration form (the “Registration Data”); (b) to maintain and promptly update the Registration Data to keep it true, accurate, current and complete; and (c) that you will comply with the rules governing Contributions in Section 6(A) below. We reserve the right to refuse registration of, or to cancel, a member account in our reasonable discretion in accordance with applicable law. You will be responsible for maintaining the confidentiality of your member account. Roomster shall not be liable for any loss that you incur as a result of someone else using your member account, either with or without your knowledge. You may be held liable for any losses incurred by Roomster due to any unauthorized use of your member account.
Member Obligations
Representations and Warranties. When you use the Service, you represent that: (i) the information you submit is truthful and accurate; (ii) your use of the Service and your use of services available on the Service do not violate any applicable law or regulation; (iii) you are at least eighteen (18) years of age and otherwise have legal capacity to legally enter into these Terms of Use, and (iv) if you are listing a room, house, apartment, or condominium (each room, house, apartment or condominium constituting an “Accommodation”) through the Service: (x) you own and/or have all necessary rights and authority to offer for rent and to rent each Accommodation that you offer through the Service; and (y) you will accurately describe the subject Accommodation, will not fail to disclose a material defect in, or material information about, the Accommodation and will ensure that the description of the Accommodation is accurate and not misleading.
Compliance with Laws. You agree that you are solely responsible for and agree to abide by all laws, rules and regulations applicable to the listings that you post through the Service, including but not limited to any and all laws, rules, regulations or other requirements relating to taxes, permits or license requirements, zoning ordinances, safety compliance and compliance with all anti-discrimination and fair housing laws, as applicable. You will be solely responsible for the collection, withholding or payment of any occupancy or other taxes that may be applicable to the Accommodation you list on the Service or use of the Service.
Verification of Authority. If you are a tenant who is listing an Accommodation through the Service, please refer to your rental contract or lease, or contact your landlord, prior to listing the Accommodation to determine whether your rental contract or lease contains restrictions that would limit your ability to list the Accommodation. Listing your Accommodation may be a violation of your rental contract or lease, and could result in legal action against you by your landlord, including possible eviction.
Insurance. We do not provide liability insurance to members in connection with the Service. Members are solely responsible for obtaining insurance coverage sufficient to protect their Accommodations. Members agree that they have or will obtain the appropriate insurance coverage sufficient to cover the rental of the Accommodations they list on the Service.
Risks Relating to the Service; Disclaimer. MEMBERS OF THE SERVICE, AND NOT ROOMSTER, ARE SOLELY RESPONSIBLE FOR ACCOMMODATIONS LISTED ON THE SERVICE. WE HAVE NO CONTROL OVER THE QUALITY, SAFETY, OR LEGALITY OF ANY ACCOMMODATION LISTED ON THE SERVICE, THE TRUTH OR ACCURACY OF A LISTING, THE ABILITY OF THE MEMBER TO OFFER THE LISTED ACCOMMODATION, OR THE ABILITY OF OTHER MEMBERS TO PAY FOR ANY TRANSACTION. WE CANNOT ENSURE THAT ANY LISTING IS ACCURATE OR THAT ANY MEMBER WILL HONOR THE TERMS OF A LISTING OR ACTUALLY COMPLETE A TRANSACTION, AND WE DO NOT MAKE ANY REPRESENTATIONS AS TO THE QUALITY, LOCATION, AVAILABILITY, SUITABILITY, OR PRICING OF ANY SPECIFIC ACCOMMODATION LISTED ON THE SERVICE. WE ARE ALSO NOT RESPONSIBLE FOR ANY DAMAGE TO REAL PROPERTY, OR DAMAGE OR LOSS OF PERSONAL PROPERTY OR PERSONAL INJURY RESULTING IN CONNECTION WITH ANY TRANSACTION ENTERED INTO THROUGH USE OF THE SERVICE.
Subscription Fees and Automatic Renewals
Basic Membership. Becoming a member of the Service and creating a profile on the Service is free. This membership level constitutes “Basic Membership”. Basic Membership allows you to search, post and contact other members of the Service for free. Basic Membership provides you with access to potential roommates in each country where the Service is made available. With the Basic Membership, you can: bookmark members you like, receive daily matches via email, get matched with other members with our keyword and personality matching services, and send emails to other members of the Service to better introduce yourself.
Full Membership. You will also have the ability to upgrade your Basic Membership by subscribing to a “Full Membership”. If you sign up for a Full Membership subscription you will have access to all of the functionality provided as part of the Basic Membership plus access to a private mailbox on the Service, access to social connections which link directly to social network profiles added by other users of the Service, such as Facebook, LinkedIn, Twitter and Instagram, and access to the text/SMS or call options that will enable you to contact other users of the Service. Full Membership rates vary depending on the length of your initial subscription. You may purchase an initial Full Membership subscription from available packages. You will be asked to choose an initial Full Membership subscription period when you sign up for Full Membership.
Automatic Renewal. If you subscribe for Full Membership, your subscription will automatically renew at the end of applicable initial subscription period, unless you elect to cancel your subscription before the end of current subscription period. The cancellation will take effect after current subscription period ends, and your account will be downgraded to Basic Membership. If you do not cancel your subscription before the end of current subscription period, we will automatically charge your payment account following the end of the applicable initial subscription period. 
How to Cancel Your Subscription. You can cancel your Full Membership subscription at any time by (i) logging in to the Service, (ii) clicking on the “Settings” button located under the “Account” tab found on your member home page, and (iii) clicking on the “Subscription” link and choosing “Cancel my Subscription”. If you cancel your Full Membership subscription, you may be entitled to a refund in accordance with Section 5(F) below, , you will have access to the Full Membership functionality until the end of the period for which payment was made, and no additional fees will be charged to your payment account following the date of cancellation. Following cancellation of a Full Membership subscription, you will continue to have access to the Basic Membership functionality unless you also delete your account in its entirety. If you have a Full Membership subscription, you will only be able to delete your account after you cancel your Full Membership subscription. All canceled accounts can be re-activated at any time in the future. Member accounts can only be cancelled by the account holder through the procedure described above. We do not accept cancellations by e-mail.
Special Cancellation Instructions for Mobile Application Users. If you sign up and pay for a Full Subscription using a third party service through which you have downloaded one of our mobile applications, e.g., the Apple App Store or Google Play Store (each, a “Third Party App Store”), your payment will be processed by the Third Party App Store through which you downloaded the mobile application and you must cancel your Service subscription through the applicable Third Party App Store.
Refund Policy. Refunds are only available if there have been no Services rendered to the User. lf you cancel your Full Membership subscription on or prior to the end of the initial subscription period, you will not receive a refund for any fees paid for the initial subscription period. However, if your Full Membership subscription automatically renews as described in Section 5(C), and if you cancel your Full Membership subscription before the end of current subscription period, you will be entitled to receive a pro rata refund of the amount you paid for the applicable subscription period based on the number of days remaining in the current subscription period. So, for example, if you cancel your subscription on day 10 of an applicable 30 day period, and you were charged $45.95 in connection with the applicable 30 day period, you will be entitled to a pro rata refund for the remaining 20 days of the 30 day period in an amount equal to $30.63. In order to request a refund, you must first cancel your subscription as described in Section 5(D) above, then contact Customer Service for refunds. A 15% handling fee will be applied to all refunds.
Rules Governing User Contributions; Prohibited Activities.
User Contributions. If you are a member of the Service and you are logged in to your member account, you may be able to submit listings, comments and content to the Service (collectively, “Contributions”). You are entirely responsible for the content of, and any harm resulting from, any Contributions that you post on or through the Service. You understand and agree that, unless expressly stated, Roomster in no way controls, verifies, or endorses any of the information provided by users and members of the Service, including links, messages, and listings. When you create or make available a Contribution on or through the Service, you represent and warrant that you:
own or have sufficient rights to post your Contributions on or through the Service;
will not post Contributions that violate our or any other person’s privacy rights, publicity rights, intellectual property rights (including without limitation copyrights) or contract rights;
have fully complied with any third-party licenses relating to Contributions and shall pay all royalties, fees and any other monies required to be paid in connection with Contributions that you post on or through the Service;
will not post Contributions that: (a) are defamatory, damaging, disruptive, unlawful, inappropriate, offensive, inaccurate, pornographic, vulgar, indecent, profane, hateful, racially or ethnically offensive, obscene, lewd, lascivious, filthy, threatening, excessively violent, harassing, or otherwise objectionable; (b) incite, encourage or threaten immediate physical harm against another, including but not limited to, Contributions that promote racism, bigotry, sexism, religious intolerance or harm against any group or individual; or (c) contain material that solicits personal information from anyone under the age of 13 or exploits anyone in a sexual or violent manner;
will not post Contributions that contain advertisements or solicit any person to buy or sell products or services; and
will not post Contributions that constitute, contain, install or attempt to install or promote spyware, malware or other computer code, whether on our or others’ computers or equipment, designated to enable you or others to gather information about or monitor the on-line or other activities of another party.
Prohibited Activities. In addition to the obligations described in Section 6(A), you agree that in connection with your use of the Service, you will not:
use the Service for any unauthorized purpose including collecting usernames and/or email addresses of other users by electronic or other means for the purpose of sending unsolicited email or other electronic communications, or engaging in unauthorized framing of, or linking to, the Service without our express written consent;
transmit chain letters, bulk or junk email or interfere with, disrupt, or create an undue burden on the Service or the networks or services connected to the Service, including without limitation, hacking into the Service, or using the system to send unsolicited or commercial emails, bulletins, comments or other communications;
impersonate any other person or entity, sell or let others use your profile or password, provide false or misleading identification or address information, or invade the privacy, or violate the personal or proprietary right, of any person or entity;
post advertisements or solicitations for jobs or employment on the Service, or otherwise use the Service to hire any person to perform work, including, without limitation, posting advertisements or solicitations for modeling jobs or talent or talent scouting positions on the Service;
post on the Service any franchise, pyramid scheme, “club membership,” distributorship or sales representative agency arrangement or other business opportunity which requires an up-front or periodic payment, pays commissions, or requires recruitment of other members, sub-distributors or sub-agents;
decompile, disassemble, modify, translate, adapt, reverse engineer, create derivative works from or sublicense the Service, or any portion thereof; or
circumvent, disable or otherwise interfere with security related features of the Service or features that prevent or restrict use or copying of any Materials (as defined in Section 8) or enforce limitations on use of the Service or the Materials on the Service.
Social Media Guidelines. If you access or use any of our social media pages on Facebook, Pinterest, Twitter, Instagram or YouTube, or post any reviews or comments regarding your use of the Service on these social media services or other third party websites, we ask you to follow the following guidelines:
please be polite and courteous. excessive name calling, profanity, fighting words, discriminatory epithets, sexual harassment, bullying, gruesome language or the like, are not acceptable.
all postings should come from a real person. we will delete any postings from our social media pages that we believe have come from fake or anonymous profiles.
please verify that all information submitted is accurate and factual. negative comments and complaints posted by you could be construed as claims about roomster or an individual and may be subject to libel laws and other legal claims.
we would like to hear about your complaints or concerns regarding the service before you share them publicly with others so that we can help resolve them for you. if you are a user and have a customer service comment, complaint, concern or idea, please email us at help@roomster.com.
<br/>
<h5>Rights in Contributions</h5>
Ownership of Contributions. We do not claim any ownership rights in the Contributions that you post on or through the Service. After posting your Contributions on the Service, you continue to retain any rights you may have in your Contributions, including any intellectual property rights or other proprietary rights associated with your Contributions, subject to the license you grant to us below.
Grant of License to Us for Contributions. By making a Contribution to the Service, you grant us a perpetual, non-exclusive (meaning you are free to license your Contribution to anyone else in addition to us), fully-paid, royalty-free (meaning that we are not required to pay you to use your Contribution), sublicensable (so that we can use affiliates, subcontractors and other partners to make the Service available to you) and worldwide (because the Internet is global in reach) license to use, modify, create derivative works of, publicly perform, publicly display, reproduce, disseminate, market and distribute the Contribution in connection with the Service, our business, or the promotion of the Service or our business in any media formats and through any media channels now known or subsequently created. If you cancel your membership or we terminate your access to the Service, your Contributions and other information and data related to your user account will no longer be accessible through the Service, however we may retain your Contributions in our archived files and your Contributions may continue to be used by and accessible to other users of the Service, for example, because your Contributions were saved or re-shared by other users of the Service.
Our Intellectual Property Rights. Except for your Contributions and the Contributions of other users of the Service, all of the content on the Service (“Materials”) and the trademarks, service marks, and logos contained on the Service, are owned by or licensed to us and are subject to copyright and other intellectual property rights under United States and foreign laws and international conventions. The Service and the Materials are for your information and personal use only and not for commercial exploitation. We reserve all rights in and to the Service and the Materials. If you download or print a copy of the Materials for your own personal use, you must retain all trademark, copyright and other proprietary notices contained in and on the Materials.
Our Management of the Service; User Misconduct
Our Right to Manage the Service. We reserve the right, but do not undertake the obligation to: (i) monitor or review the Service for violations of these Terms of Use and for compliance with our policies; (ii) report to law enforcement authorities and/or take legal action against anyone who violates these Terms of Use; (iii) refuse, restrict access to or the availability of, or remove, delete, edit or disable (to the extent technologically feasible) any Contribution or any portion thereof; (iv) manage the Service in a manner designed to protect our and third parties’ rights and property or to facilitate the proper functioning of the Service; (v) screen our users or members, or attempt to verify the statements of our users or members and/or (vi) monitor disputes between you and other users or to terminate or block you and other users for violating these Terms of Use.
Interactions with other Users. We cannot and do not verify the identity of users or members of the Service or the accuracy of any information that members provide. You are solely responsible for determining the identity and suitability of the other users or members with whom you interact when using the Service. We do not investigate or verify any user’s or member’s reputation, conduct, morality, criminal background, or any information members may submit to the Services. You are solely responsible for your interactions with other users and members of the Service. Please note that there are risks that may arise when dealing with strangers, including persons who may be acting under false pretenses. Please choose carefully the information you post on the Service and that you give to other users and members of the Service. You are discouraged from publicly posting your telephone number or street address on the Service. Information posted to the Service by other users and members of the Service may be offensive, harmful or inaccurate, and in some cases may be mislabeled or deceptively labeled. You assume all risks associated with dealing with other users and members with whom you come in contact through the Service. Opinions and other statements included in users’ and members’ Contributions do not represent the opinions or statements of Roomster and the posting of a Contribution on the Service does not constitute Roomster’s support or endorsement of any opinions or statements expressed in the applicable Contribution.
Scams. If you are reported and then verified to be operating a cashier check or wire transfer scam, or operating any other scam in connection with the Service, Roomster will report this conduct to the FTC and the FBI Internet Crime Complaint Center. Roomster encourages our users to be mindful of potential scams and to use caution if another user or member of the Service engages in any of the following activities: (i) a user or member offers a high-value (but fake) cashier's check, (ii) a user or member requests payment via Western Union or MoneyGram, (iii) a user or member offers to send you a cashier's check and asks you to wire money back to them, or (iv) a user or member suggests use of an online escrow service.
Reporting Member Misconduct. If you think that another member of the Service is acting or has acted inappropriately by, for example, engaging in offensive, violent or sexually inappropriate conduct or in a scam or other illegal conduct, we encourage you to report that member to the appropriate authorities. We also request that you report this behavior to us by contacting us at help@roomster.com. Please note that although we encourage you to report misconduct to us, we are not responsible or liable for members’ actions, and we are not obligated to take any action if you report member misconduct to us.
Our Right to Terminate Users. WITHOUT LIMITING ANY OTHER PROVISION OF these Terms of Use, WE RESERVE THE RIGHT TO, IN OUR SOLE DISCRETION, AND WITHOUT NOTICE OR LIABILITY, DENY ACCESS TO AND USE OF the Service TO ANY PERSON FOR ANY REASON OR FOR NO REASON AT ALL, as permited by applicable law, INCLUDING WITHOUT LIMITATION FOR BREACH OF ANY REPRESENTATION, WARRANTY OR COVENANT CONTAINED IN these Terms of Use, OR OF ANY APPLICABLE LAW OR REGULATION.
Third Party App Stores. You acknowledge and agree that the availability of the Service may be dependent on Third Party App Stores. You acknowledge that these Terms of Use are between you and Roomster and not with the applicable Third Party App Store. Each Third Party App Store may have its own terms and conditions to which you must agree before downloading the Service from it. You agree to comply with, and your license to use the Service is conditioned upon, your compliance with, the applicable Third Party App Store terms and conditions. To the extent that other terms and conditions from the applicable Third Party App Store are less restrictive than, or otherwise conflict with, the terms and conditions of these Terms of Use, the more restrictive or conflicting terms and conditions in these Terms of Use will apply.
Third Party Sites. The Service may contain links to websites operated by third parties (“Third Party Sites”), and you may be able to share Contributions or other information with Third Party Sites through links on the Service; however, we do not own or operate the Third Party Sites, and we have not reviewed, and cannot review, all of the material, including goods or services, made available through Third Party Sites. The availability of these links on the Service does not represent, warrant or imply that we endorse any Third Party Sites or any materials, opinions, goods or services available on them. Third party materials accessed through or used by means of the Third Party Sites may also be protected by copyright and other intellectual property laws. THESE TERMS OF USE DO NOT APPLY TO THIRD PARTY SITES. BEFORE VISITING A THIRD PARTY SITE THROUGH LINKS OR OTHER MEANS PROVIDED ON OR THROUGH THE SERVICE, YOU SHOULD REVIEW THE THIRD PARTY SITE’S TERMS AND CONDITIONS AND PRIVACY POLICY, AND INFORM YOURSELF OF THE REGULATIONS, POLICIES AND PRACTICES OF THESE THIRD PARTY SITES.</p>
    </div>
  )
}
